services:
    app:
        container_name: app-1
        build:
            context: .
            dockerfile: Dockerfile

        deploy:
            resources:
                limits:
                    memory: 8G # Set the maximum memory limit
                    cpus: "5.0" # Set the maximum CPU limit
                reservations:
                    memory: 4G # Set the guaranteed memory (less than or equal to `limits.memory`)
                    cpus: "4.0"

        volumes:
            - .:/srv/node/app
            - ./src/infra/database/prisma:/srv/node/app/src/infra/database/prisma
        ports:
            #- "3000:3000"
            - "9229:9229"
        networks:
            - app-network
            - app-mongo-network
            - app-redis-network
        environment:
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - MONGO_PORT=${MONGO_PORT:-27017}
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:latest
        environment:
            MONGO_URI: ${MONGO_URI}
            MONGO_DB: ${MONGO_DB}
        volumes:
            - mongo_data:/data/db
        networks:
            - app-mongo-network

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
            - ./nginx/certs:/etc/nginx/certs:ro
            - ./html:/usr/share/nginx/html:ro
            - ./static:/usr/share/nginx/static:ro
        depends_on:
            - app
        networks:
            - app-network

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - app-redis-network

networks:
    app-network:
        driver: bridge

    app-mongo-network:
        driver: bridge

    app-redis-network:
        driver: bridge

volumes:
    mongo_data:
