services:
    app:
        container_name: app-1
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/srv/node/app
            - ./src/infra/database/prisma:/srv/node/app/src/infra/database/prisma
        ports:
            #- "3000:3000"
            - "9229:9229"
        networks:
            - app-network
        environment:
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - MONGO_PORT=${MONGO_PORT:-27017}
        depends_on:
            - postgres
            - mongo

    postgres:
        container_name: postgres-1
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-app_database}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    mongo:
        image: mongo:latest
        environment:
            MONGO_URI: ${MONGO_URI}
            MONGO_DB: ${MONGO_DB}
        volumes:
            - mongo_data:/data/db
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./html:/usr/share/nginx/html:ro
            - ./static:/usr/share/nginx/static:ro
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
    mongo_data:
